"""
tests/test_legacy_mtnobsc_overlay.py
---------------------------------------
Checks the legacy MTN OBSC comparison overlay: the data file itself, and
the guarantee that it stays display-only.

The data file (data/boundaries/legacy_mtnobsc.json) is generated by
scripts/build_legacy.py from VOR strings -- see
data/boundaries/LEGACY_MTNOBSC.md for the caveats that come with it. The
geometry tests skip when the file isn't in the checkout, following
test_mtn_obsc.py's precedent for the terrain grid; the display-only test
does not, because that one is about this repo's code and holds whether or
not the data has landed.
"""

import json
import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

REPO_ROOT = Path(__file__).resolve().parent.parent
LEGACY_PATH = REPO_ROOT / "data" / "boundaries" / "legacy_mtnobsc.json"
NAVAIDS_FIXTURE = REPO_ROOT / "tests" / "fixtures" / "navaids_subset.csv"
EXPECTED_FEATURES = {"Appalachians", "Rockies", "CentralValleyCutout"}

# CONUS with a generous margin -- the same bounding box the terrain grid
# uses (pipeline.fetch_terrain.CONUS_BOUNDS). A vertex outside this is a
# resolution error in the VOR strings, not a wide area.
CONUS_WEST, CONUS_SOUTH, CONUS_EAST, CONUS_NORTH = -126.0, 22.0, -65.0, 50.0


def _legacy_geojson_bytes():
    if not LEGACY_PATH.exists():
        pytest.skip(
            "data/boundaries/legacy_mtnobsc.json not in this checkout -- generate it with "
            "scripts/build_legacy.py (see data/boundaries/LEGACY_MTNOBSC.md)"
        )
    return LEGACY_PATH.read_bytes()


def _legacy_geojson():
    if not LEGACY_PATH.exists():
        pytest.skip(
            "data/boundaries/legacy_mtnobsc.json not in this checkout -- generate it with "
            "scripts/build_legacy.py (see data/boundaries/LEGACY_MTNOBSC.md)"
        )
    return json.loads(LEGACY_PATH.read_text())


def _rings(geometry):
    if geometry["type"] == "Polygon":
        return list(geometry["coordinates"])
    if geometry["type"] == "MultiPolygon":
        return [ring for part in geometry["coordinates"] for ring in part]
    raise AssertionError(f"unexpected geometry type {geometry['type']}")


def test_file_loads_and_holds_the_three_expected_features():
    data = _legacy_geojson()
    assert data["type"] == "FeatureCollection"
    names = {f["properties"]["name"] for f in data["features"]}
    assert names == EXPECTED_FEATURES, f"expected {sorted(EXPECTED_FEATURES)}, got {sorted(names)}"
    assert len(data["features"]) == 3


def test_every_ring_is_closed():
    """GeoJSON requires the first and last position of a ring to match."""
    for feature in _legacy_geojson()["features"]:
        name = feature["properties"]["name"]
        for index, ring in enumerate(_rings(feature["geometry"])):
            assert len(ring) >= 4, f"{name} ring {index} has {len(ring)} positions; a ring needs 4"
            assert ring[0] == ring[-1], f"{name} ring {index} is not closed"


def test_every_vertex_is_inside_conus():
    """
    A vertex outside the CONUS box means a VOR identifier resolved to the
    wrong navaid -- the exact failure mode LEGACY_MTNOBSC.md flags for
    the eight colliding identifiers, which were resolved US-first.
    """
    for feature in _legacy_geojson()["features"]:
        name = feature["properties"]["name"]
        for ring in _rings(feature["geometry"]):
            for lon, lat in ring:
                assert CONUS_WEST <= lon <= CONUS_EAST, f"{name}: longitude {lon} is outside CONUS"
                assert CONUS_SOUTH <= lat <= CONUS_NORTH, f"{name}: latitude {lat} is outside CONUS"


def test_running_the_build_script_reproduces_the_committed_file_byte_for_byte():
    """
    The committed GeoJSON and the script that generates it are two
    artifacts of one source (the VOR strings in build_legacy.py), and
    nothing but this test keeps them in step. They were already out of
    step once: the script emitted the identifier under `area` while the
    file and the viewer used `name`.

    Run as a subprocess, through the real CLI, because that is what a
    person regenerating this actually types -- importing build() would
    skip argument handling and the output path, which is where the last
    round of drift lived.

    navaids_subset.csv is a verbatim subset of OurAirports' navaids.csv
    (URL in the script header), trimmed to the rows these three strings
    resolve -- every US/CA row for a referenced ident, so the table's own
    duplicate handling still applies. Verified byte-identical output
    against the full 1.5 MB upstream table when it was made.
    """
    import subprocess
    import sys
    import tempfile

    committed = _legacy_geojson_bytes()
    with tempfile.TemporaryDirectory() as tmp:
        out = Path(tmp) / "regenerated.json"
        result = subprocess.run(
            [sys.executable, str(REPO_ROOT / "scripts" / "build_legacy.py"),
             "--navaids", str(NAVAIDS_FIXTURE), "--out", str(out), "--quiet"],
            capture_output=True, text=True,
        )
        assert result.returncode == 0, f"build_legacy.py failed:\n{result.stderr}"
        regenerated = out.read_bytes()

    assert regenerated == committed, (
        "regenerating no longer reproduces data/boundaries/legacy_mtnobsc.json. "
        "If the VOR strings or the navaid table changed on purpose, commit the "
        "regenerated file; if not, the script and the data have drifted apart."
    )


def test_the_build_script_writes_into_the_repo_by_default():
    """
    It used to write to a hardcoded /home/claude/... path, so a
    regeneration landed nowhere near the file it was meant to replace.
    """
    import ast

    source = (REPO_ROOT / "scripts" / "build_legacy.py").read_text()
    assert "/home/claude" not in source, "the hardcoded personal output path is back"

    tree = ast.parse(source)
    default_out = [
        node for node in ast.walk(tree)
        if isinstance(node, ast.Assign)
        and any(isinstance(t, ast.Name) and t.id == "DEFAULT_OUT" for t in node.targets)
    ]
    assert default_out, "DEFAULT_OUT is gone"
    assert "legacy_mtnobsc.json" in ast.unparse(default_out[0]), ast.unparse(default_out[0])
    assert "REPO_ROOT" in ast.unparse(default_out[0]), "the default output path is not repo-relative"


def test_the_navaid_source_is_documented_where_someone_regenerating_will_look():
    """The table is not vendored, so the script has to say where to get it."""
    source = (REPO_ROOT / "scripts" / "build_legacy.py").read_text()
    header = source[:source.index('"""', source.index('"""') + 3)]
    assert "ourairports-data/main/navaids.csv" in header, (
        "the navaid table's download URL is not in the script header"
    )


def test_the_overlay_is_not_wired_into_any_gate_or_mask():
    """
    The overlay is for looking at, not for filtering by. Terrain-derived
    areas outside the legacy boundaries are not assumed wrong -- the
    legacy areas are broad-brush because the resolution to do better
    never existed, and surfacing relief they miss is a goal of this tool.
    Wiring this file into a gate would quietly delete that.

    So: nothing under pipeline/ may reference it. The viewer and its API
    route are allowed, and are the only things that should be.
    """
    referring = []
    for path in sorted((REPO_ROOT / "pipeline").rglob("*.py")):
        text = path.read_text()
        if "legacy_mtnobsc" in text or "LEGACY_MTNOBSC" in text:
            referring.append(str(path.relative_to(REPO_ROOT)))

    assert not referring, (
        f"the legacy overlay is referenced by {referring} -- it is display-only and must not "
        "reach any gate, mask or filter (see data/boundaries/LEGACY_MTNOBSC.md)"
    )


def test_the_caveats_travel_with_the_data():
    """
    The geometry has three known soft spots (true-vs-magnetic offset
    bearings, the YSC substitution, eight US-first identifier
    collisions). They decide how much the overlay should be trusted, so
    they have to be written down next to it rather than living in a
    commit message.
    """
    doc = (REPO_ROOT / "data" / "boundaries" / "LEGACY_MTNOBSC.md").read_text()
    for needle in ("TRUE", "70NW_PQI", "YSC", "US-first", "Display only", "CentralValleyCutout"):
        assert needle in doc, f"LEGACY_MTNOBSC.md no longer mentions {needle!r}"


if __name__ == "__main__":
    sys.exit(pytest.main([__file__, "-v"]))
